# Generated by Django 5.0 on 2023-12-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('translation_en', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('translation_en', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=70)),
                ('category', models.CharField(blank=True, choices=[('NA', 'Nomen'), ('AD', 'Adjektive'), ('VE', 'Verben'), ('MVE', 'Modal Verben')], max_length=5, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Maskulin'), ('F', 'Feminin'), ('N', 'Neutral')], max_length=3, null=True)),
                ('translation_en', models.CharField(max_length=70)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
