# Generated by Django 5.0 on 2023-12-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='f_form',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Feminin (Form)'),
        ),
        migrations.AddField(
            model_name='word',
            name='p_form',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Plural (Form)'),
        ),
    ]
