# Generated by Django 5.0 on 2023-12-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_word_f_form_word_p_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, choices=[('NA', 'Nomen'), ('AD', 'Adjektive'), ('VE', 'Verben'), ('MVE', 'Modal Verben'), ('INTER', 'Interjektionen')], max_length=5, null=True),
        ),
    ]
