# Generated by Django 5.0 on 2023-12-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0006_alter_word_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, choices=[('NA', 'Nomen'), ('AD', 'Adjektive'), ('VE', 'Verben'), ('MVE', 'Modal Verben'), ('INTER', 'Interjektionen'), ('ADV', 'Adverb'), ('PRO', 'Pronomen'), ('FPRO', 'Fragepronomen'), ('KONJ', 'Konjunktion')], max_length=5, null=True),
        ),
    ]
