# Generated by Django 5.0 on 2024-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0007_alter_word_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NA", "Nomen"),
                    ("AD", "Adjektive"),
                    ("VE", "Verben"),
                    ("MVE", "Modal Verben"),
                    ("INTER", "Interjektionen"),
                    ("ADV", "Adverb"),
                    ("PRO", "Pronomen"),
                    ("FPRO", "Fragepronomen"),
                    ("KONJ", "Konjunktion"),
                    ("PREP", "Präposition"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
